# Generated by Django 5.0.1 on 2024-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_journal_content_journal_location_journal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
