# Generated by Django 5.0.1 on 2024-02-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='content',
        ),
    ]
